services:
    front:
      container_name: front
      image: ayoubakb/jobportail-front:latest
      build: 
        context: ./front
      ports:
        - 3000:3000
      environment :
        - REACT_APP_CLIENT_URI=${REACT_APP_CLIENT_URI}
        - REACT_APP_SERVER_URI=${REACT_APP_SERVER_URI}
      depends_on :
        - back
      networks: 
        - job_portailNetwork
      
    back:
      container_name: back
      image: ayoubakb/jobportail-back:latest
      build: ./back
      ports:
        - 9090:9090
      environment: 
        - DB_URI=mongodb://db/jobPortail
      depends_on:
        - db
      networks:
        - job_portailNetwork

    db:
      container_name: db
      image: mongo:latest
      environment:
        - MONGO_INITDB_DATABASE:jobPortail
      ports:
        - 27017:27017
      volumes : 
        - ./init.js:/docker-entrypoint-initdb.d/init.js
        - job_portailVolume:/data/db
      networks:
        - job_portailNetwork

volumes:
  job_portailVolume:
    driver: local 
networks:
  job_portailNetwork:
    driver: bridge

      